<?php

$labels = array();
$labels['filter']                       = 'Filters';
$labels['filterManage']                 = 'Manage incoming mail filters';
$labels['filterName']                   = 'Filter name';
$labels['filterList']                   = 'Filters List';
$labels['filterFrom']                   = 'From';
$labels['filterSubject']                = 'Subject';
$labels['filterTo']                     = 'To';
$labels['filterReply']                  = 'Reply Address';
$labels['filterBody']                   = 'Body';
$labels['filterHeader']                 = 'Any Header';
$labels['filterRecipient']              = 'Any Recipient';
$labels['filterEquals']                 = 'equals';
$labels['filterRegex']                  = 'matches regular expression';
$labels['filterContains']               = 'contains';
$labels['filterNotcontains']            = 'does not contain';
$labels['filterBeginwith']              = 'begins with';
$labels['filterEndswith']               = 'ends with';
$labels['filterNotbeginwith']           = 'does not begin with';
$labels['filterNotendwith']             = 'does not end with';
$labels['filterNotmatch']               = 'does not match';
$labels['filterDeliver']                = 'Deliver to Folder';
$labels['filterRedirect']               = 'Redirect to Email';
$labels['filterFail']                   = 'Fail with message';
$labels['filterStop']                   = 'Stop Processing rules';
$labels['filterNew']                    = 'New filter';

// TO BE EDITED
$messages = array();
$messages['filterunknownerror'] = 'Unknown server error';
$messages['filterconnerror'] = 'Unable to connect to managesieve server';
$messages['filterdeleteerror'] = 'Unable to delete filter. Server error occured';
$messages['filterdeleted'] = 'Filter deleted successfully';
$messages['filtersaved'] = 'Filter saved successfully';
$messages['filtersaveerror'] = 'Unable to save filter. Server error occured';
$messages['filterdeleteconfirm'] = 'Do you really want to delete selected filter?';
$messages['ruledeleteconfirm'] = 'Are you sure, you want to delete selected rule?';
$messages['actiondeleteconfirm'] = 'Are you sure, you want to delete selected action?';
$messages['forbiddenchars'] = 'Forbidden characters in field';
$messages['cannotbeempty'] = 'Field cannot be empty';
$messages['setactivateerror'] = 'Unable to activate selected filters set. Server error occured';
$messages['setdeactivateerror'] = 'Unable to deactivate selected filters set. Server error occured';
$messages['setdeleteerror'] = 'Unable to delete selected filters set. Server error occured';
$messages['setactivated'] = 'Filters set activated successfully';
$messages['setdeactivated'] = 'Filters set deactivated successfully';
$messages['setdeleted'] = 'Filters set deleted successfully';
$messages['setdeleteconfirm'] = 'Are you sure, you want to delete selected filters set?';
$messages['setcreateerror'] = 'Unable to create filters set. Server error occured';
$messages['setcreated'] = 'Filters set created successfully';
$messages['emptyname'] = 'Unable to create filters set. Empty set name';
$messages['nametoolong'] = 'Unable to create filters set. Name too long'
?>
